deployment:
  tasks:
  - export DEPLOYPATH=/home/projectcode/public_html/vueapp
  - /bin/cp -r ./* $DEPLOYPATH #copy all from root
  - /bin/cp -r ./.eslintrc.js $DEPLOYPATH
  -  /bin/cp -r ./.htaccess $DEPLOYPATH